### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jamesdundon** [prajwalsouza/Epidemic-Simulation#1]
Hi, love the simulator. 

Is it possible to get a table of values for SIR. I would like my students to use your simulator to investigate a variable and see the effect on your simulator. It would help them to be able to compare values rather than just looking at the graphs. Also, perhaps a option to pause after a specific number of steps. 

Thanks.

**Comment by prajwalsouza** [comment]
Hi. [Updated version](https://prajwalsouza.github.io/Experiments/Epidemic-Simulations/Epidemic-Simulation-Masks-and-CSV-Export.html) to include CSV export. :) 

Although the updated version also has a mask effectiveness feature (Last two sliders) and circles around the particle indicate presence of masks. You can remove this, but setting "% of the population wears mask" to 0%.  

![image](https://user-images.githubusercontent.com/25048805/161405581-f5d9df8b-6fad-4c32-a7cf-c28405150aff.png)

Hope this works. :)

**Comment by jamesdundon** [comment]
Amazing. Thank you. 🙌
